import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./component/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="fixed inset-0 bg-red-400 h-16">
          <nav className="flex justify-center gap-3 items-center h-16">
            <Link href="/">Home</Link>
            <Link href="/products">Products</Link>
            <Link href="/categories">Category</Link>
          </nav>
        </header>

        <Navbar />
        
        <main className='mt-16'> 
        {children}
        </main>
       
      </body>
    </html>
  );
}
